/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM5_H_
#define WAVEFORM5_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM5)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[315614];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[157807];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[105205];
#endif

#endif

#endif
