/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM_THEONLYSOLUTION_H_
#define WAVEFORM_THEONLYSOLUTION_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM_THEONLYSOLUTION)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[463863];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[231932];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[154621];
#endif

#endif

#endif
