/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM4_H_
#define WAVEFORM4_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM4)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[341447];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[170724];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[113816];
#endif

#endif

#endif
