/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM7_H_
#define WAVEFORM7_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM7)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[354416];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[177208];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[118139];
#endif

#endif

#endif
