/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM_JUL_H_
#define WAVEFORM_JUL_H_
#include <stdint.h>
#include "config.h"

#if AUDIO_SAMPLE_RATE == 16000
#define JUL_AVAILABLE
extern const int16_t waveform_jul[190705];
#endif

#endif
