/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM3_H_
#define WAVEFORM3_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM3)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[460842];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[230421];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[153614];
#endif

#endif

#endif
