/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM2_H_
#define WAVEFORM2_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM2)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[464226];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[232113];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[154742];
#endif

#endif

#endif
