/** @file Automatically generated wavetable. Generated by gen_wavetable.m */
#ifndef WAVEFORM6_H_
#define WAVEFORM6_H_
#include <stdint.h>
#include "config.h"

#if defined(AUDIO_WAVEFORM_WAVEFORM6)

#if AUDIO_SAMPLE_RATE == 48000
extern const int16_t waveform[308164];
#endif

#if AUDIO_SAMPLE_RATE == 24000
extern const int16_t waveform[154082];
#endif

#if AUDIO_SAMPLE_RATE == 16000
extern const int16_t waveform[102722];
#endif

#endif

#endif
